### PR TITLE
Fixed dependencies for Laravel 5.8

### PR DESCRIPTION
**Pull request by BoGnY**

### CODE REVIEW

**Comment by vonec** [comment]
can you commit this ?

**Comment by BoGnY** [comment]
[**@vonec**](https://github.com/vonec) commented on [#44](https://github.com/zgabievi/laravel-promocodes/pull/44#issuecomment-478370748 "2019-03-31T19:07:52Z - Replied by Github Reply Comments"):
> can you commit this ?

No sorry, only the code owner can merge this pull request...
You can override this by specifying a custom repo in your `composer.json` that link to my fork.. so the original package will be overwritten by mine (that have the dependencies updated for laravel 5.8):

```json
{
    ...
    "repositories": [
        {
            "type": "github",
            "url":  "https://github.com/bogny/laravel-promocodes"
        }
    ],
    "require": {
        "zgabievi/promocodes": "dev-master"
    }
    ...
}
```

When @zgabievi merge this pull request, you can restore your `composer.json`.. 
More info: https://getcomposer.org/doc/04-schema.md#repositories

**Comment by zgabievi** [comment]
Thank you for your help. I've merged it

**Comment by vonec** [comment]
hi @zgabievi  is this released ? waiting to check it out

**Comment by zgabievi** [comment]
Hi @vonec , Yes it is released as 2.2.0

**Comment by vonec** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package zgabievi/promocodes 2.2.0 exists as zgabievi/promocodes[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.1, 0.5.4, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 5.1.x-dev, dev-master] but these are rejected by your constraint.

**Comment by vonec** [comment]
i think this is not yet pushed on to github and released :( waiting ...

**Comment by vonec** [comment]
https://github.com/zgabievi/laravel-promocodes/commit/024674ffd81813249fe50f4c88bd255505665b1f doesnt have the composer changes can you please look into this :)

**Comment by zgabievi** [comment]
Ok, I've tested and I could install [2.2.1](https://github.com/zgabievi/laravel-promocodes/tree/2.2.1) and it has support for Laravel 5.8

**Comment by vonec** [comment]
got it thank you ... really useful package

**Comment by zgabievi** [comment]
Thank you. I have some plans to improve it, but couldn't manage to find free time for it. It's really nice that there are people like @BoGnY, who's ready to help.

**Comment by BoGnY** [comment]
open source is beautiful for that 😊

**Pull request closed without merging**
